name: Build
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: selt-hosted
        steps:
            - name: Set tp QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Builx
              uses: docker/setup-buildx-action@v2
